services:
  # 1. Our Relational Database
  postgres:
    image: postgres:15
    container_name: mailstream-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Change this to match your application.properties password
      POSTGRES_DB: mailstream_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Our In-Memory Cache / Rate Limiter
  redis:
    image: redis:7
    container_name: mailstream-redis
    ports:
      - "6379:6379"

  # 3. Apache Kafka (Message Broker) - OFFICIAL IMAGE
  kafka:
    image: apache/kafka:3.7.0
    container_name: mailstream-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 4. Local Mail Catcher (For safe testing)
  mailpit:
    image: axllent/mailpit
    container_name: mailstream-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

# This ensures your database data doesn't disappear when you stop your containers
volumes:
  postgres_data: